# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=15)),
                ('body_part', models.CharField(max_length=15)),
                ('patient', models.CharField(max_length=100)),
                ('bone_image', models.FileField(upload_to='')),
            ],
        ),
    ]
