# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0002_xray_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='probability',
            field=models.FloatField(default=0),
        ),
    ]
